<!-- SideNav slide-out button -->
<a href="#" data-activates="slide-out" class="btn btn-primary p-3 button-collapse"><i
    class="fas fa-bars"></i></a>
<div id="slide-out" class="side-nav fixed">
  <ul class="custom-scrollbar">
    <li>
      <li><a href="#info" data-toggle="tab" class="active">INFO</a></li>
      <li><a href="#story" data-toggle="tab">STORY</a></li>
      <li id='cpu'><a href="#resources" data-toggle="tab">RESOURCES</a></li>
    </li>
</div>
<!--/. Sidebar navigation -->
